#!/bin/bash

curlResult=$(mktemp)

curl -s 'https://www.midsussex.gov.uk/waste-recycling/bin-collection/' \
  -H 'authority: www.midsussex.gov.uk' \
  -H 'cache-control: max-age=0' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'origin: https://www.midsussex.gov.uk' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryIftXC885DLNi8k4r' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-fetch-dest: document' \
  -H 'referer: https://www.midsussex.gov.uk/waste-recycling/bin-collection/' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  --data-raw $'------WebKitFormBoundaryIftXC885DLNi8k4r\r\nContent-Disposition: form-data; name="PostCodeStep.strAddressSearch"\r\n\r\nbn6 8bg\r\n------WebKitFormBoundaryIftXC885DLNi8k4r\r\nContent-Disposition: form-data; name="AddressStep.strAddressSelect"\r\n\r\n2 NEWLANDS CLOSE BN6 8BG\r\n------WebKitFormBoundaryIftXC885DLNi8k4r\r\nContent-Disposition: form-data; name="Next"\r\n\r\ntrue\r\n------WebKitFormBoundaryIftXC885DLNi8k4r\r\nContent-Disposition: form-data; name="StepIndex"\r\n\r\n1\r\n------WebKitFormBoundaryIftXC885DLNi8k4r\r\nContent-Disposition: form-data; name="ufprt"\r\n\r\n72C560B1858C41929FCE5FB77300C6F7B5900D5FCC999596CD4FB16F9203FC5DF6AEB5538A581ED51A673770201FEE4991D7FF0F5294BA65746661F135EFC2C7D101A90D697D1A3B4FC871DAE8DFB37C8DD1F9D55BC862421FFEE4639085D0EF3D407E0BA0D69CD2E63C0A6A2EEB997373B36D46455890500AFD620CF0C0222748F1DA915F26100745BDD27F4F6CDC0F\r\n------WebKitFormBoundaryIftXC885DLNi8k4r--\r\n' \
  --compressed > ${curlResult}

if [ "$?" != "0" ]; then
	echo "Curl failed."
	exit 1
else
	binColour=$(grep "$(date -d "+1 day" +"%A %d %B %Y")" ${curlResult} -B2 | head -1 | awk -F'>' '{ print $2 }' | awk -F'<' '{ print $1 }' | tr '[:upper:]' '[:lower:]')
	echo "Tomorrow is ${binColour} bin day."
fi

/usr/local/bin/telegram "Tomorrow is ${binColour} bin day."
