#!/bin/bash

if [ ! -f /usr/local/bin/telegram ]; then 
 echo "Could not find telegram binary."
 exit 1
fi

curlResult=$(mktemp)

curl 'https://www.midsussex.gov.uk/waste-recycling/bin-collection/' \
  -H 'authority: www.midsussex.gov.uk' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'cache-control: max-age=0' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundaryMPVhKz024psfKBDW' \
  -H 'cookie: .AspNetCore.Antiforgery.9fXoN5jHCXs=CfDJ8BYOjofrcRxKmwtx7KIuYJkqodLcND9dJp3RkFSs7QW68Qk2mOUrPv-y_8BiWiXWaRSK2Y2fDAA63BWISMbQqkARSUrZOw4qnCyy0xyYkKtyZ8jv5tY4uPSI6rNAD51iY6NCV6uI5vjIRihcjXxG5KM; CookieControl={"necessaryCookies":[],"optionalCookies":{"analytics":"accepted"},"statement":{},"consentDate":1694977386101,"consentExpiry":90,"interactedWith":true,"user":"EC8B390F-24DA-43E1-B1E0-77F47E87E227"}; nmstat=d82e67ee-9630-10c3-cef6-6a71c27186de' \
  -H 'origin: https://www.midsussex.gov.uk' \
  -H 'pragma: show-debug-headers' \
  -H 'referer: https://www.midsussex.gov.uk/waste-recycling/bin-collection/' \
  -H 'sec-ch-ua: "Chromium";v="116", "Not)A;Brand";v="24", "Google Chrome";v="116"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36' \
  --data-raw $'------WebKitFormBoundaryMPVhKz024psfKBDW\r\nContent-Disposition: form-data; name="StrAddressSelect"\r\n\r\n2 NEWLANDS CLOSE BN6 8BG\r\n------WebKitFormBoundaryMPVhKz024psfKBDW\r\nContent-Disposition: form-data; name="submit"\r\n\r\n\r\n------WebKitFormBoundaryMPVhKz024psfKBDW\r\nContent-Disposition: form-data; name="__RequestVerificationToken"\r\n\r\nCfDJ8BYOjofrcRxKmwtx7KIuYJljlKikgtkvKGdooaEOWtTxzbYEiNwyXuH7cLs-52Lwjs0okaxXIPw9aoohLv04gITDw_30IV0HrCW9SnwgAhX98jMFa9sYhw7cB_VDmEumcADsfpX3jlGBxYtR9xdt-eY\r\n------WebKitFormBoundaryMPVhKz024psfKBDW\r\nContent-Disposition: form-data; name="ufprt"\r\n\r\nCfDJ8BYOjofrcRxKmwtx7KIuYJkRwNXUegLw0druGbLB_hxRa8dDrgE_Oe66aMWCSeFoWI2SlZAo-Rob7eji93oDE9Li4clZ4AIZedW9SXwJUeJpHKmPVIpxLk1To9Q1H8wYENLFrgqCy9_NJNVtDoMw91B8l-h-txgFj4WI5JgoCJw9\r\n------WebKitFormBoundaryMPVhKz024psfKBDW--\r\n' \
  --compressed > ${curlResult}

if [ "$?" != "0" ]; then
	echo "Curl failed!"
	exit 1
else
	binColour=$(grep "$(date -d "+1 day" +"%A %d %B %Y")" ${curlResult} -B2 /tmp/tmp.jB48ErHTEe | head -2 | tail -1 | awk -F'>' '{ print $2 }' | awk -F'<' '{ print $1 }' | tr '[:upper:]' '[:lower:]')
	if [ ! -z "${binColour}" ]; then
		echo "Tomorrow is ${binColour} day."
		/usr/local/bin/telegram "Tomorrow is ${binColour} day."
	else
		echo "No bin collections tomorrow."
	fi
fi
