#!/bin/bash
#
# chkconfig: 2345 99 00
# description: generic j2ee application
#
# generic init script for java -jar style application
# replace 'application' with the relevant name.
#
#

. /etc/rc.d/init.d/functions

JAVA=/....../jdk1.7.0_51/bin/java
APPLICATION_HOME=/servers/application-envname
PIDFILE=/var/run/application.pid

start() {

                if [ -s ${PIDFILE} ]; then
                        echo "application already running. pid $(cat /var/run/application.pid)"
                        exit 1
                fi
                echo "Starting application"
                $JAVA -jar $APPLICATION_HOME/application.jar 2>/$APPLICATION_HOME/logs/stderr.log 1>/$APPLICATION_HOME/logs/stdout.log &
                PID=$!
                echo $PID > /var/run/application.pid
                if [ -s /var/run/application.pid ]; then
                        echo_success
			echo
                else
                        echo_failure
			echo
                fi
}

stop() {
        if [ -f ${PIDFILE} ]; then
            echo "Stopping seyren"
            kill $(cat ${PIDFILE})
			if [ "$?" != "0" ]; then 
				echo_failure
				echo
				exit 1
			fi               
            rm -f ${PIDFILE}
			if [ "$?" != "0" ]; then 
				echo_failure
				echo
				exit 1
			else
				echo_success
				echo
				exit 0
			fi
        else
            echo_failure
			echo
			exit 1
        fi
}


status() {
		if [ -f ${PIDFILE} ]; then
			PID=$(cat ${PIDFILE} 2>/dev/null)
			if [ -d "/proc/$PID" ]; then
				echo "application is running. pid ${PID}"
      				exit 0
    			else
      				echo "application has a stale pid file."
      				exit 1
    			fi
  		else
			echo "application is stopped."
  		fi

}

case $1 in
        start)
                start
		;;
        stop)
                stop
		;;
	restart)
		stop
		sleep 2
		start
		;;
	status)
		status
		;;
        *)
                echo "Usage: $0 [start|stop|restart|status]"
esac
