#!/bin/bash

working=/home/ben/iplayer
exe=$working/getme
target=$working/$(date +%d-%m-%Y)

if [ ! -d "$target" ]; then mkdir -p $target ; fi
if [ -f $exe ];        then rm -f $exe;        fi

SaveIFS=$IFS
IFS=','

while read name;
 do echo get_iplayer \"$name\" --get --nopurge --modes=best --output $target >> $exe ;
done < ${working}/names

sh $exe

for file in *partial.mp4*; do
 rm -v $file
done

echo "Sending the files with rsync ..."

if [ "$1" != '--no-rsync' ]; then
 rsync -rzv $target nexus9:/sdcard/iplayer/
fi

IFS=$SaveIFS

unlink ${working}/latest
ln -s ${target} ${working}/latest
